#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ORANGE 0 
#define RED 1 
#define YELLOW 2 
#define WHITE 3 
#define BLUE 4 
#define GREEN 5 

#define STATES 3674160
#define HASH_TABLE_SIZE (2 * STATES)
#define GOD 11
#define EXTRA_MOVES 4 //3 
#define MAX_MOVES (GOD + EXTRA_MOVES)
#define MOVES 9
#define ANGLES 24
#define INFINITY 374269
#define UNIQUE_STATES 154608
#define SOLUTIONS 5 //5

#define MOVE_R_NORMAL 0
#define MOVE_R_INVERSE 1
#define MOVE_R_DOUBLE 2
#define MOVE_U_NORMAL 3
#define MOVE_U_INVERSE 4
#define MOVE_U_DOUBLE 5
#define MOVE_F_NORMAL 6
#define MOVE_F_INVERSE 7
#define MOVE_F_DOUBLE 8

#define ROTATION_X_NORMAL 0
#define ROTATION_X_INVERSE 1
#define ROTATION_X_DOUBLE 2
#define ROTATION_Y_NORMAL 3
#define ROTATION_Y_INVERSE 4
#define ROTATION_Y_DOUBLE 5
#define ROTATION_Z_NORMAL 6
#define ROTATION_Z_INVERSE 7
#define ROTATION_Z_DOUBLE 8

#define GRIPS 3
#define GRIP_THUMB_DOWN 0
#define GRIP_THUMB_FRONT 1
#define GRIP_THUMB_UP 2

#define TRICKS 11
#define TRICK_NONE 0
#define TRICK_LEFT_PINCH 1
#define TRICK_LEFT_INDEX 2
#define TRICK_LEFT_MIDDLE 3
#define TRICK_LEFT_DOUBLE 4
#define TRICK_LEFT_PUSH 5
#define TRICK_RIGHT_PINCH 6
#define TRICK_RIGHT_INDEX 7
#define TRICK_RIGHT_MIDDLE 8
#define TRICK_RIGHT_DOUBLE 9
#define TRICK_RIGHT_PUSH 10

#define COORDINATES (GRIPS * TRICKS * TRICKS)


#define UNDEFINED_UF INFINITY

#define PICKUP 100
#define GOOD_REGRIP 25
#define BAD_REGRIP 75

#define QUARTER_WRIST 100
#define HALF_WRIST 150

#define QUARTER_REGRIP 125

/*
#define NONE_NONE
#define NONE_PINCH
#define NONE_INDEX
#define NONE_MIDDLE
#define NONE_DOUBLE
#define NONE_PUSH
#define PINCH_NONE
#define PINCH_PINCH
#define PINCH_INDEX
*/
#define PINCH_MIDDLE 200 
/*
#define PINCH_DOUBLE
#define PINCH_PUSH
#define INDEX_NONE
#define INDEX_PINCH
#define INDEX_INDEX
#define INDEX_MIDDLE
#define INDEX_DOUBLE
#define INDEX_PUSH
#define MIDDLE_NONE
#define MIDDLE_PINCH
#define MIDDLE_INDEX
#define MIDDLE_MIDDLE
#define MIDDLE_DOUBLE
#define MIDDLE_PUSH
#define DOUBLE_NONE
#define DOUBLE_PINCH
#define DOUBLE_INDEX
#define DOUBLE_MIDDLE
#define DOUBLE_DOUBLE
#define DOUBLE_PUSH
#define PUSH_NONE
#define PUSH_PINCH
#define PUSH_INDEX
#define PUSH_MIDDLE
#define PUSH_DOUBLE
#define PUSH_PUSH
*/

//#define NONE_NONE_NONE
#define NONE_NONE_PINCH 125 
#define NONE_NONE_INDEX 125 
#define NONE_NONE_MIDDLE INFINITY //new
#define NONE_NONE_DOUBLE 175 
#define NONE_NONE_PUSH 175 

//#define PINCH_NONE_NONE
#define PINCH_NONE_PINCH 175 
#define PINCH_NONE_INDEX 175
#define PINCH_NONE_MIDDLE 150
#define PINCH_NONE_DOUBLE 225
#define PINCH_NONE_PUSH 200 

//#define INDEX_NONE_NONE
#define INDEX_NONE_PINCH 175
#define INDEX_NONE_INDEX 175
#define INDEX_NONE_MIDDLE 150
#define INDEX_NONE_DOUBLE 225
#define INDEX_NONE_PUSH 200 

//#define MIDDLE_NONE_NONE
#define MIDDLE_NONE_PINCH 250
#define MIDDLE_NONE_INDEX 250
#define MIDDLE_NONE_MIDDLE INFINITY //new
#define MIDDLE_NONE_DOUBLE 300
#define MIDDLE_NONE_PUSH 250 

//#define DOUBLE_NONE_NONE 
#define DOUBLE_NONE_PINCH 250
#define DOUBLE_NONE_INDEX 250
#define DOUBLE_NONE_MIDDLE INFINITY //new
#define DOUBLE_NONE_DOUBLE 300 
#define DOUBLE_NONE_PUSH 250 

//#define PUSH_NONE_NONE
#define PUSH_NONE_PINCH INFINITY 
#define PUSH_NONE_INDEX 150 
#define PUSH_NONE_MIDDLE INFINITY //new
#define PUSH_NONE_DOUBLE 200 
#define PUSH_NONE_PUSH INFINITY 


#endif